[FacelessDetectionIncome.X2FacelessIncomeHelper]

; If the default value of config "REDUCTION_ABILITIES_BONUS_MULTI" in LWOTC file "XComLW_Activities.ini" was changed and is no longer 0.1
; Then this config may be changed to the same value so that the calculation is done accurately
REDUCTION_ABILITIES_BONUS_MULTI=0.1