[Engine.ScriptPackages]
+NonNativePackages=FacelessDetectionIncome

[UnrealEd.EditorEngine]
;+ModEditPackages=X2WOTCCommunityHighlander
;+ModEditPackages=X2WOTCCommunityHighlander_DLC_2
+ModEditPackages=LW_Tuple
+ModEditPackages=NewPromotionScreenbyDefault
+ModEditPackages=XModBase_Interfaces
+ModEditPackages=XModBase_Core_3_0_0
+ModEditPackages=LW_XModBase
+ModEditPackages=WallClimbOverride
+ModEditPackages=LWUtilities
+ModEditPackages=ModConfigMenuAPI
+ModEditPackages=BetterSecondWaveSupport
+ModEditPackages=LW_XCGS_ModOptions
+ModEditPackages=LW_XCGS_ToolboxOptions
+ModEditPackages=LW_SMGPack_Integrated
+ModEditPackages=LW_LaserPack_Integrated
+ModEditPackages=PI_Integrated
+ModEditPackages=LW_PerkPack_Integrated
+ModEditPackages=LW_OfficerPack_Integrated
+ModEditPackages=LW_AlienPack_Integrated
+ModEditPackages=LW_Toolbox_Integrated
+ModEditPackages=LW_WeaponsAndArmor
+ModEditPackages=LW_FactionBalance
+ModEditPackages=LW_Overhaul
+ModEditPackages=LW_Tutorial
+ModEditPackages=LWModJamFixes

;[Engine.Engine]
;+ModClassOverrides=(BaseGameClass="SomeClass", ModClass="FacelessDetectionIncome.SomeClass_Override")